apiVersion: v1
kind: Service
metadata:
  name: testapp1-service
spec:
  type: LoadBalancer
  selector:
    app: testapp1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
    
