apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
data:
  hazelcast.xml: |
    <hazelcast>
      <network>
        <join>
          <multicast enabled="false" />
          <tcp-ip enabled="true">
            <interface>eth0</interface>
            <member-list>
              <member>hazelcast-service.default.svc.cluster.local</member>
            </member-list>
          </tcp-ip>
        </join>
      </network>
    </hazelcast>
